### ISSUE TITLE
how to use it with systemJs

### ISSUE THREAD

**Issue by hem19** [SimonBiggs/angular-phosphor#1]
@SimonBiggs I am trying to use phosphor-dockpanel in my application using your example. But my application is still using System JS and you are using WebPack.

Can you make a sample app of how to use it with SystemJS or if you can guide me in the right direction.

Thanks in advance.

**Comment by SimonBiggs** [comment]
Hi, I never really got this working to my satisfaction anyway. Sorry I won't be able to help you with this.

**Comment by hem19** [comment]
@SimonBiggs Thanks for your reply. If you know any other docking control for angular 2, let me know. Though I found a control named 'Golden Layout' but it require using jQuery which I am trying to avoid.

**Comment by SimonBiggs** [comment]
In the end Phosphor wasn't actually for angular either. I was trying to
monkey patch it in. It probably would have worked in the end, but the end
result wasn't going to be Mobil responsive. That was the show stopper
really.
